"""empty message

Revision ID: e397c08c2646
Revises: 48aa4e59a485
Create Date: 2021-05-13 14:27:35.163673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e397c08c2646'
down_revision = '48aa4e59a485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('title', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_description_created_on'), 'job_description', ['created_on'], unique=False)
    op.drop_index('ix_message_data_created_on', table_name='message_data')
    op.drop_table('message_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('prediction', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_data_created_on', 'message_data', ['created_on'], unique=False)
    op.drop_index(op.f('ix_job_description_created_on'), table_name='job_description')
    op.drop_table('job_description')
    # ### end Alembic commands ###
